//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR1_0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardGames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoardGames()
        {
            this.ListOfGames = new HashSet<ListOfGames>();
            this.Tournaments = new HashSet<Tournaments>();
        }
    
        public int ID { get; set; }
        public string NameGame { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Genre { get; set; }
        public Nullable<int> Thematics { get; set; }
        public Nullable<int> AgeLimit { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> Exclusivity { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Genre Genre1 { get; set; }
        public virtual Thematics Thematics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOfGames> ListOfGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tournaments> Tournaments { get; set; }
    }
}
