//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR1_0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameNights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameNights()
        {
            this.GameNightsApplications = new HashSet<GameNightsApplications>();
            this.GameNightsParticipiants = new HashSet<GameNightsParticipiants>();
            this.ListOfGames = new HashSet<ListOfGames>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> Responsible { get; set; }
        public Nullable<int> MinimumNumberOfParticipants { get; set; }
        public Nullable<int> MaximumNumberOfParticipants { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameNightsApplications> GameNightsApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameNightsParticipiants> GameNightsParticipiants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOfGames> ListOfGames { get; set; }
    }
}
