//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR1_0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameNightsApplications
    {
        public int ID { get; set; }
        public Nullable<int> User { get; set; }
        public Nullable<int> GameNights { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Reason { get; set; }
    
        public virtual GameNights GameNights1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
