//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR1_0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournaments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournaments()
        {
            this.TournamentsParticipiants = new HashSet<TournamentsParticipiants>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public Nullable<int> AgeLimit { get; set; }
        public Nullable<int> BoardGames { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Responsible { get; set; }
    
        public virtual BoardGames BoardGames1 { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentsParticipiants> TournamentsParticipiants { get; set; }
    }
}
